language: java
rvm:
  - 1.9.3
jdk:
  - openjdk6
env:
  - CASSANDRA_VERSION=1.0
script:
  - bundle exec rake
before_script:
  - java -version
  - rvm use 1.9.3
  - bundle install
  - bundle exec rake 'cassandra:start[daemonize]'
