language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
env:
  - CASSANDRA_VERSION=1.2
  - CASSANDRA_VERSION=1.1
  - CASSANDRA_VERSION=1.0
  - CASSANDRA_VERSION=0.8
  - CASSANDRA_VERSION=0.7 JDK6=true
  - CASSANDRA_VERSION=0.6 JDK6=true
before_script:
  - bash -c '[[ -n $JDK6 ]] && jdk_switcher use openjdk6'
  - java -version
  - bundle exec rake 'cassandra:start[daemonize]'
