language: java
jdk:
  - openjdk6
env:
  - CASSANDRA_VERSION=0.6 RVM_RUBY=1.9.3
  - CASSANDRA_VERSION=0.6 RVM_RUBY=1.8.7
  - CASSANDRA_VERSION=0.7 RVM_RUBY=1.9.3
  - CASSANDRA_VERSION=0.7 RVM_RUBY=1.8.7
  - CASSANDRA_VERSION=0.8 RVM_RUBY=1.9.3
  - CASSANDRA_VERSION=0.8 RVM_RUBY=1.8.7
  - CASSANDRA_VERSION=1.0 RVM_RUBY=1.9.3
  - CASSANDRA_VERSION=1.0 RVM_RUBY=1.8.7
script:
  - bundle exec rake
before_script:
  - java -version
  - rvm use "$RVM_RUBY"
  - bundle install
  - bundle exec rake 'cassandra:start[daemonize]'
